// src/data/mockflights.tsx
import type { FlightOffer } from "../types/flights";

export const mockFlights: FlightOffer[] = [
  // Melbourne → Sydney
  {
    id: "1",
    airline: "Qantas",
    airlineCode: "QF",
    logo: "🦘",
    flightNumber: "QF403",
    from: "Melbourne",
    fromCode: "MEL",
    to: "Sydney",
    toCode: "SYD",
    departureTime: "08:10",
    arrivalTime: "09:35",
    duration: "1h 25m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 189,
    originalPrice: 240,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.8,
    deal: "Best Value",
  },
  {
    id: "2",
    airline: "Virgin Australia",
    airlineCode: "VA",
    logo: "💜",
    flightNumber: "VA821",
    from: "Melbourne",
    fromCode: "MEL",
    to: "Sydney",
    toCode: "SYD",
    departureTime: "11:00",
    arrivalTime: "12:30",
    duration: "1h 30m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 175,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.5,
    deal: "Cheapest",
  },
  {
    id: "3",
    airline: "Jetstar",
    airlineCode: "JQ",
    logo: "⭐",
    flightNumber: "JQ501",
    from: "Melbourne",
    fromCode: "MEL",
    to: "Sydney",
    toCode: "SYD",
    departureTime: "14:15",
    arrivalTime: "15:50",
    duration: "1h 35m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 129,
    currency: "AUD",
    baggage: "7kg",
    wifi: false,
    rating: 3.8,
  },
  // Melbourne → Singapore
  {
    id: "4",
    airline: "Singapore Airlines",
    airlineCode: "SQ",
    logo: "🇸🇬",
    flightNumber: "SQ218",
    from: "Melbourne",
    fromCode: "MEL",
    to: "Singapore",
    toCode: "SIN",
    departureTime: "06:20",
    arrivalTime: "11:45",
    duration: "8h 25m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 740,
    originalPrice: 920,
    currency: "AUD",
    baggage: "30kg",
    wifi: true,
    rating: 4.9,
    deal: "Best Value",
  },
  {
    id: "5",
    airline: "Jetstar",
    airlineCode: "JQ",
    logo: "⭐",
    flightNumber: "JQ07",
    from: "Melbourne",
    fromCode: "MEL",
    to: "Singapore",
    toCode: "SIN",
    departureTime: "23:55",
    arrivalTime: "06:00+1",
    duration: "8h 05m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 490,
    currency: "AUD",
    baggage: "7kg",
    wifi: false,
    rating: 3.7,
    deal: "Cheapest",
  },
  // Melbourne → London
  {
    id: "6",
    airline: "Emirates",
    airlineCode: "EK",
    logo: "🇦🇪",
    flightNumber: "EK407",
    from: "Melbourne",
    fromCode: "MEL",
    to: "London",
    toCode: "LHR",
    departureTime: "09:15",
    arrivalTime: "22:00+1",
    duration: "23h 45m",
    stops: 1,
    stopLabel: "1 stop · Dubai",
    price: 1295,
    currency: "AUD",
    baggage: "30kg",
    wifi: true,
    rating: 4.9,
    deal: "Cheapest",
  },
  {
    id: "7",
    airline: "Qantas",
    airlineCode: "QF",
    logo: "🦘",
    flightNumber: "QF1",
    from: "Melbourne",
    fromCode: "MEL",
    to: "London",
    toCode: "LHR",
    departureTime: "16:30",
    arrivalTime: "05:10+1",
    duration: "21h 40m",
    stops: 1,
    stopLabel: "1 stop · Singapore",
    price: 1680,
    originalPrice: 2100,
    currency: "AUD",
    baggage: "30kg",
    wifi: true,
    rating: 4.8,
    deal: "Best Value",
  },
  // Sydney → Melbourne
  {
    id: "8",
    airline: "Qantas",
    airlineCode: "QF",
    logo: "🦘",
    flightNumber: "QF404",
    from: "Sydney",
    fromCode: "SYD",
    to: "Melbourne",
    toCode: "MEL",
    departureTime: "07:00",
    arrivalTime: "08:25",
    duration: "1h 25m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 195,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.8,
  },
  {
    id: "9",
    airline: "Virgin Australia",
    airlineCode: "VA",
    logo: "💜",
    flightNumber: "VA820",
    from: "Sydney",
    fromCode: "SYD",
    to: "Melbourne",
    toCode: "MEL",
    departureTime: "13:30",
    arrivalTime: "15:00",
    duration: "1h 30m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 165,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.5,
    deal: "Cheapest",
  },
  // Sydney → Tokyo
  {
    id: "10",
    airline: "Japan Airlines",
    airlineCode: "JL",
    logo: "🇯🇵",
    flightNumber: "JL772",
    from: "Sydney",
    fromCode: "SYD",
    to: "Tokyo",
    toCode: "NRT",
    departureTime: "21:15",
    arrivalTime: "07:30+1",
    duration: "10h 15m",
    stops: 0,
    stopLabel: "Non-stop",
    price: 980,
    originalPrice: 1250,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.9,
    deal: "Best Value",
  },
  {
    id: "11",
    airline: "Cathay Pacific",
    airlineCode: "CX",
    logo: "🇭🇰",
    flightNumber: "CX138",
    from: "Sydney",
    fromCode: "SYD",
    to: "Tokyo",
    toCode: "NRT",
    departureTime: "11:00",
    arrivalTime: "04:30+1",
    duration: "17h 30m",
    stops: 1,
    stopLabel: "1 stop · Hong Kong",
    price: 750,
    currency: "AUD",
    baggage: "23kg",
    wifi: true,
    rating: 4.7,
    deal: "Cheapest",
  },
];
